### PR TITLE
Remove Cargo.lock

### PR DESCRIPTION
**Pull request by GitGhillie**
It's not necessary for libraries and will make the diffs less noisy

### CODE REVIEW

**Comment by SolarLiner** [comment]
I'll note I fully disagree with this. Build reproducibility is still important for libraries, especially non-stable ones, where a difference in dependency resolution can cause conflicts and introduce bugs. I'm okay with noisy diffs on the lock, and it's fine to just ignore it entirely. ~~I never agreed with Rust guidelines on this for the reason above~~. It's also a problem for build systems with reproducibility in mind (like NixOS) because they rely on Cargo.lock already being derived as their source of truth when downloading dependencies.

I'll approve because it's the decision that Bevy took, and so it makes sense to do the same. But I'll groan and complain about it a little bit 😆 

EDIT: The guidelines have [changed Aug. 2023](https://blog.rust-lang.org/2023/08/29/committing-lockfiles.html), and lockfiles are not advised to be ignored for libraries anymore.

**Review by SolarLiner — APPROVED** [review]

**Comment by GitGhillie** [comment]
Well, TIL. I could swear it wasn't too long ago that I did `cargo new --lib` and it added the lock file to the gitignore, but I guess I'm misremembering. Feel free to close this :)

**Comment by GitGhillie** [comment]
Oops I closed it, but I think you were leaning in that direction anyways xd

**Comment by SolarLiner** [comment]
Yeah either case we'll remove it during up streaming probably

**Pull request closed without merging**
